version: 2

project_name: sweep

before:
  hooks:
    - go mod tidy

builds:
  - id: sweep
    main: ./cmd/sweep
    binary: sweep
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: sweepd
    main: ./cmd/sweepd
    binary: sweepd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - CHANGELOG*

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: jamesainslie
    name: sweep
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## sweep {{ .Version }}

    Disk space analyzer with TUI and daemon mode.
  footer: |
    ---
    Full changelog: https://github.com/jamesainslie/sweep/compare/{{ .PreviousTag }}...{{ .Tag }}
