// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sweep/v1/sweep.proto

package sweepv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndexState int32

const (
	IndexState_INDEX_STATE_UNKNOWN     IndexState = 0
	IndexState_INDEX_STATE_NOT_INDEXED IndexState = 1
	IndexState_INDEX_STATE_INDEXING    IndexState = 2
	IndexState_INDEX_STATE_READY       IndexState = 3
	IndexState_INDEX_STATE_STALE       IndexState = 4
)

// Enum value maps for IndexState.
var (
	IndexState_name = map[int32]string{
		0: "INDEX_STATE_UNKNOWN",
		1: "INDEX_STATE_NOT_INDEXED",
		2: "INDEX_STATE_INDEXING",
		3: "INDEX_STATE_READY",
		4: "INDEX_STATE_STALE",
	}
	IndexState_value = map[string]int32{
		"INDEX_STATE_UNKNOWN":     0,
		"INDEX_STATE_NOT_INDEXED": 1,
		"INDEX_STATE_INDEXING":    2,
		"INDEX_STATE_READY":       3,
		"INDEX_STATE_STALE":       4,
	}
)

func (x IndexState) Enum() *IndexState {
	p := new(IndexState)
	*p = x
	return p
}

func (x IndexState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexState) Descriptor() protoreflect.EnumDescriptor {
	return file_sweep_v1_sweep_proto_enumTypes[0].Descriptor()
}

func (IndexState) Type() protoreflect.EnumType {
	return &file_sweep_v1_sweep_proto_enumTypes[0]
}

func (x IndexState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexState.Descriptor instead.
func (IndexState) EnumDescriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{0}
}

type GetLargeFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	MinSize       int64                  `protobuf:"varint,2,opt,name=min_size,json=minSize,proto3" json:"min_size,omitempty"`
	Exclude       []string               `protobuf:"bytes,3,rep,name=exclude,proto3" json:"exclude,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLargeFilesRequest) Reset() {
	*x = GetLargeFilesRequest{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLargeFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLargeFilesRequest) ProtoMessage() {}

func (x *GetLargeFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLargeFilesRequest.ProtoReflect.Descriptor instead.
func (*GetLargeFilesRequest) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{0}
}

func (x *GetLargeFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetLargeFilesRequest) GetMinSize() int64 {
	if x != nil {
		return x.MinSize
	}
	return 0
}

func (x *GetLargeFilesRequest) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *GetLargeFilesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       int64                  `protobuf:"varint,3,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	CreateTime    int64                  `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Owner         string                 `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	Group         string                 `protobuf:"bytes,6,opt,name=group,proto3" json:"group,omitempty"`
	Mode          uint32                 `protobuf:"varint,7,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{1}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *FileInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *FileInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *FileInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *FileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type GetIndexStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexStatusRequest) Reset() {
	*x = GetIndexStatusRequest{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexStatusRequest) ProtoMessage() {}

func (x *GetIndexStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexStatusRequest.ProtoReflect.Descriptor instead.
func (*GetIndexStatusRequest) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{2}
}

func (x *GetIndexStatusRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type IndexStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	State         IndexState             `protobuf:"varint,2,opt,name=state,proto3,enum=sweep.v1.IndexState" json:"state,omitempty"`
	FilesIndexed  int64                  `protobuf:"varint,3,opt,name=files_indexed,json=filesIndexed,proto3" json:"files_indexed,omitempty"`
	DirsIndexed   int64                  `protobuf:"varint,4,opt,name=dirs_indexed,json=dirsIndexed,proto3" json:"dirs_indexed,omitempty"`
	TotalSize     int64                  `protobuf:"varint,5,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	LastUpdated   int64                  `protobuf:"varint,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Progress      float32                `protobuf:"fixed32,7,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexStatus) Reset() {
	*x = IndexStatus{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexStatus) ProtoMessage() {}

func (x *IndexStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexStatus.ProtoReflect.Descriptor instead.
func (*IndexStatus) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{3}
}

func (x *IndexStatus) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *IndexStatus) GetState() IndexState {
	if x != nil {
		return x.State
	}
	return IndexState_INDEX_STATE_UNKNOWN
}

func (x *IndexStatus) GetFilesIndexed() int64 {
	if x != nil {
		return x.FilesIndexed
	}
	return 0
}

func (x *IndexStatus) GetDirsIndexed() int64 {
	if x != nil {
		return x.DirsIndexed
	}
	return 0
}

func (x *IndexStatus) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *IndexStatus) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

func (x *IndexStatus) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type TriggerIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerIndexRequest) Reset() {
	*x = TriggerIndexRequest{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerIndexRequest) ProtoMessage() {}

func (x *TriggerIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerIndexRequest.ProtoReflect.Descriptor instead.
func (*TriggerIndexRequest) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerIndexRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TriggerIndexRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type TriggerIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Started       bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerIndexResponse) Reset() {
	*x = TriggerIndexResponse{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerIndexResponse) ProtoMessage() {}

func (x *TriggerIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerIndexResponse.ProtoReflect.Descriptor instead.
func (*TriggerIndexResponse) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{5}
}

func (x *TriggerIndexResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *TriggerIndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WatchIndexProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchIndexProgressRequest) Reset() {
	*x = WatchIndexProgressRequest{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchIndexProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchIndexProgressRequest) ProtoMessage() {}

func (x *WatchIndexProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchIndexProgressRequest.ProtoReflect.Descriptor instead.
func (*WatchIndexProgressRequest) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{6}
}

func (x *WatchIndexProgressRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type IndexProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	State         IndexState             `protobuf:"varint,2,opt,name=state,proto3,enum=sweep.v1.IndexState" json:"state,omitempty"`
	DirsScanned   int64                  `protobuf:"varint,3,opt,name=dirs_scanned,json=dirsScanned,proto3" json:"dirs_scanned,omitempty"`
	FilesScanned  int64                  `protobuf:"varint,4,opt,name=files_scanned,json=filesScanned,proto3" json:"files_scanned,omitempty"`
	CurrentPath   string                 `protobuf:"bytes,5,opt,name=current_path,json=currentPath,proto3" json:"current_path,omitempty"`
	Progress      float32                `protobuf:"fixed32,6,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexProgress) Reset() {
	*x = IndexProgress{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexProgress) ProtoMessage() {}

func (x *IndexProgress) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexProgress.ProtoReflect.Descriptor instead.
func (*IndexProgress) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{7}
}

func (x *IndexProgress) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *IndexProgress) GetState() IndexState {
	if x != nil {
		return x.State
	}
	return IndexState_INDEX_STATE_UNKNOWN
}

func (x *IndexProgress) GetDirsScanned() int64 {
	if x != nil {
		return x.DirsScanned
	}
	return 0
}

func (x *IndexProgress) GetFilesScanned() int64 {
	if x != nil {
		return x.FilesScanned
	}
	return 0
}

func (x *IndexProgress) GetCurrentPath() string {
	if x != nil {
		return x.CurrentPath
	}
	return ""
}

func (x *IndexProgress) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type GetDaemonStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDaemonStatusRequest) Reset() {
	*x = GetDaemonStatusRequest{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDaemonStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDaemonStatusRequest) ProtoMessage() {}

func (x *GetDaemonStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDaemonStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDaemonStatusRequest) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{8}
}

type DaemonStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Running           bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	UptimeSeconds     int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	MemoryBytes       int64                  `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	WatchedPaths      []string               `protobuf:"bytes,4,rep,name=watched_paths,json=watchedPaths,proto3" json:"watched_paths,omitempty"`
	CacheSizeBytes    int64                  `protobuf:"varint,5,opt,name=cache_size_bytes,json=cacheSizeBytes,proto3" json:"cache_size_bytes,omitempty"`
	TotalFilesIndexed int64                  `protobuf:"varint,6,opt,name=total_files_indexed,json=totalFilesIndexed,proto3" json:"total_files_indexed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DaemonStatus) Reset() {
	*x = DaemonStatus{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonStatus) ProtoMessage() {}

func (x *DaemonStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonStatus.ProtoReflect.Descriptor instead.
func (*DaemonStatus) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{9}
}

func (x *DaemonStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *DaemonStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *DaemonStatus) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *DaemonStatus) GetWatchedPaths() []string {
	if x != nil {
		return x.WatchedPaths
	}
	return nil
}

func (x *DaemonStatus) GetCacheSizeBytes() int64 {
	if x != nil {
		return x.CacheSizeBytes
	}
	return 0
}

func (x *DaemonStatus) GetTotalFilesIndexed() int64 {
	if x != nil {
		return x.TotalFilesIndexed
	}
	return 0
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{10}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{11}
}

func (x *ShutdownResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ClearCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCacheRequest) Reset() {
	*x = ClearCacheRequest{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCacheRequest) ProtoMessage() {}

func (x *ClearCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCacheRequest.ProtoReflect.Descriptor instead.
func (*ClearCacheRequest) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{12}
}

func (x *ClearCacheRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ClearCacheResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EntriesCleared int64                  `protobuf:"varint,2,opt,name=entries_cleared,json=entriesCleared,proto3" json:"entries_cleared,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClearCacheResponse) Reset() {
	*x = ClearCacheResponse{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCacheResponse) ProtoMessage() {}

func (x *ClearCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCacheResponse.ProtoReflect.Descriptor instead.
func (*ClearCacheResponse) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{13}
}

func (x *ClearCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClearCacheResponse) GetEntriesCleared() int64 {
	if x != nil {
		return x.EntriesCleared
	}
	return 0
}

var File_sweep_v1_sweep_proto protoreflect.FileDescriptor

const file_sweep_v1_sweep_proto_rawDesc = "" +
	"\n" +
	"\x14sweep/v1/sweep.proto\x12\bsweep.v1\"u\n" +
	"\x14GetLargeFilesRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\bmin_size\x18\x02 \x01(\x03R\aminSize\x12\x18\n" +
	"\aexclude\x18\x03 \x03(\tR\aexclude\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\xae\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x19\n" +
	"\bmod_time\x18\x03 \x01(\x03R\amodTime\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\x03R\n" +
	"createTime\x12\x14\n" +
	"\x05owner\x18\x05 \x01(\tR\x05owner\x12\x14\n" +
	"\x05group\x18\x06 \x01(\tR\x05group\x12\x12\n" +
	"\x04mode\x18\a \x01(\rR\x04mode\"+\n" +
	"\x15GetIndexStatusRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xf3\x01\n" +
	"\vIndexStatus\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12*\n" +
	"\x05state\x18\x02 \x01(\x0e2\x14.sweep.v1.IndexStateR\x05state\x12#\n" +
	"\rfiles_indexed\x18\x03 \x01(\x03R\ffilesIndexed\x12!\n" +
	"\fdirs_indexed\x18\x04 \x01(\x03R\vdirsIndexed\x12\x1d\n" +
	"\n" +
	"total_size\x18\x05 \x01(\x03R\ttotalSize\x12!\n" +
	"\flast_updated\x18\x06 \x01(\x03R\vlastUpdated\x12\x1a\n" +
	"\bprogress\x18\a \x01(\x02R\bprogress\"?\n" +
	"\x13TriggerIndexRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"J\n" +
	"\x14TriggerIndexResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x19WatchIndexProgressRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xd6\x01\n" +
	"\rIndexProgress\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12*\n" +
	"\x05state\x18\x02 \x01(\x0e2\x14.sweep.v1.IndexStateR\x05state\x12!\n" +
	"\fdirs_scanned\x18\x03 \x01(\x03R\vdirsScanned\x12#\n" +
	"\rfiles_scanned\x18\x04 \x01(\x03R\ffilesScanned\x12!\n" +
	"\fcurrent_path\x18\x05 \x01(\tR\vcurrentPath\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x02R\bprogress\"\x18\n" +
	"\x16GetDaemonStatusRequest\"\xf1\x01\n" +
	"\fDaemonStatus\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x03R\vmemoryBytes\x12#\n" +
	"\rwatched_paths\x18\x04 \x03(\tR\fwatchedPaths\x12(\n" +
	"\x10cache_size_bytes\x18\x05 \x01(\x03R\x0ecacheSizeBytes\x12.\n" +
	"\x13total_files_indexed\x18\x06 \x01(\x03R\x11totalFilesIndexed\"\x11\n" +
	"\x0fShutdownRequest\",\n" +
	"\x10ShutdownResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"'\n" +
	"\x11ClearCacheRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"W\n" +
	"\x12ClearCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fentries_cleared\x18\x02 \x01(\x03R\x0eentriesCleared*\x8a\x01\n" +
	"\n" +
	"IndexState\x12\x17\n" +
	"\x13INDEX_STATE_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17INDEX_STATE_NOT_INDEXED\x10\x01\x12\x18\n" +
	"\x14INDEX_STATE_INDEXING\x10\x02\x12\x15\n" +
	"\x11INDEX_STATE_READY\x10\x03\x12\x15\n" +
	"\x11INDEX_STATE_STALE\x10\x042\x9c\x04\n" +
	"\vSweepDaemon\x12E\n" +
	"\rGetLargeFiles\x12\x1e.sweep.v1.GetLargeFilesRequest\x1a\x12.sweep.v1.FileInfo0\x01\x12H\n" +
	"\x0eGetIndexStatus\x12\x1f.sweep.v1.GetIndexStatusRequest\x1a\x15.sweep.v1.IndexStatus\x12M\n" +
	"\fTriggerIndex\x12\x1d.sweep.v1.TriggerIndexRequest\x1a\x1e.sweep.v1.TriggerIndexResponse\x12T\n" +
	"\x12WatchIndexProgress\x12#.sweep.v1.WatchIndexProgressRequest\x1a\x17.sweep.v1.IndexProgress0\x01\x12K\n" +
	"\x0fGetDaemonStatus\x12 .sweep.v1.GetDaemonStatusRequest\x1a\x16.sweep.v1.DaemonStatus\x12A\n" +
	"\bShutdown\x12\x19.sweep.v1.ShutdownRequest\x1a\x1a.sweep.v1.ShutdownResponse\x12G\n" +
	"\n" +
	"ClearCache\x12\x1b.sweep.v1.ClearCacheRequest\x1a\x1c.sweep.v1.ClearCacheResponseB\x93\x01\n" +
	"\fcom.sweep.v1B\n" +
	"SweepProtoP\x01Z6github.com/jamesainslie/sweep/pkg/api/sweep/v1;sweepv1\xa2\x02\x03SXX\xaa\x02\bSweep.V1\xca\x02\bSweep\\V1\xe2\x02\x14Sweep\\V1\\GPBMetadata\xea\x02\tSweep::V1b\x06proto3"

var (
	file_sweep_v1_sweep_proto_rawDescOnce sync.Once
	file_sweep_v1_sweep_proto_rawDescData []byte
)

func file_sweep_v1_sweep_proto_rawDescGZIP() []byte {
	file_sweep_v1_sweep_proto_rawDescOnce.Do(func() {
		file_sweep_v1_sweep_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sweep_v1_sweep_proto_rawDesc), len(file_sweep_v1_sweep_proto_rawDesc)))
	})
	return file_sweep_v1_sweep_proto_rawDescData
}

var file_sweep_v1_sweep_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sweep_v1_sweep_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_sweep_v1_sweep_proto_goTypes = []any{
	(IndexState)(0),                   // 0: sweep.v1.IndexState
	(*GetLargeFilesRequest)(nil),      // 1: sweep.v1.GetLargeFilesRequest
	(*FileInfo)(nil),                  // 2: sweep.v1.FileInfo
	(*GetIndexStatusRequest)(nil),     // 3: sweep.v1.GetIndexStatusRequest
	(*IndexStatus)(nil),               // 4: sweep.v1.IndexStatus
	(*TriggerIndexRequest)(nil),       // 5: sweep.v1.TriggerIndexRequest
	(*TriggerIndexResponse)(nil),      // 6: sweep.v1.TriggerIndexResponse
	(*WatchIndexProgressRequest)(nil), // 7: sweep.v1.WatchIndexProgressRequest
	(*IndexProgress)(nil),             // 8: sweep.v1.IndexProgress
	(*GetDaemonStatusRequest)(nil),    // 9: sweep.v1.GetDaemonStatusRequest
	(*DaemonStatus)(nil),              // 10: sweep.v1.DaemonStatus
	(*ShutdownRequest)(nil),           // 11: sweep.v1.ShutdownRequest
	(*ShutdownResponse)(nil),          // 12: sweep.v1.ShutdownResponse
	(*ClearCacheRequest)(nil),         // 13: sweep.v1.ClearCacheRequest
	(*ClearCacheResponse)(nil),        // 14: sweep.v1.ClearCacheResponse
}
var file_sweep_v1_sweep_proto_depIdxs = []int32{
	0,  // 0: sweep.v1.IndexStatus.state:type_name -> sweep.v1.IndexState
	0,  // 1: sweep.v1.IndexProgress.state:type_name -> sweep.v1.IndexState
	1,  // 2: sweep.v1.SweepDaemon.GetLargeFiles:input_type -> sweep.v1.GetLargeFilesRequest
	3,  // 3: sweep.v1.SweepDaemon.GetIndexStatus:input_type -> sweep.v1.GetIndexStatusRequest
	5,  // 4: sweep.v1.SweepDaemon.TriggerIndex:input_type -> sweep.v1.TriggerIndexRequest
	7,  // 5: sweep.v1.SweepDaemon.WatchIndexProgress:input_type -> sweep.v1.WatchIndexProgressRequest
	9,  // 6: sweep.v1.SweepDaemon.GetDaemonStatus:input_type -> sweep.v1.GetDaemonStatusRequest
	11, // 7: sweep.v1.SweepDaemon.Shutdown:input_type -> sweep.v1.ShutdownRequest
	13, // 8: sweep.v1.SweepDaemon.ClearCache:input_type -> sweep.v1.ClearCacheRequest
	2,  // 9: sweep.v1.SweepDaemon.GetLargeFiles:output_type -> sweep.v1.FileInfo
	4,  // 10: sweep.v1.SweepDaemon.GetIndexStatus:output_type -> sweep.v1.IndexStatus
	6,  // 11: sweep.v1.SweepDaemon.TriggerIndex:output_type -> sweep.v1.TriggerIndexResponse
	8,  // 12: sweep.v1.SweepDaemon.WatchIndexProgress:output_type -> sweep.v1.IndexProgress
	10, // 13: sweep.v1.SweepDaemon.GetDaemonStatus:output_type -> sweep.v1.DaemonStatus
	12, // 14: sweep.v1.SweepDaemon.Shutdown:output_type -> sweep.v1.ShutdownResponse
	14, // 15: sweep.v1.SweepDaemon.ClearCache:output_type -> sweep.v1.ClearCacheResponse
	9,  // [9:16] is the sub-list for method output_type
	2,  // [2:9] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_sweep_v1_sweep_proto_init() }
func file_sweep_v1_sweep_proto_init() {
	if File_sweep_v1_sweep_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sweep_v1_sweep_proto_rawDesc), len(file_sweep_v1_sweep_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sweep_v1_sweep_proto_goTypes,
		DependencyIndexes: file_sweep_v1_sweep_proto_depIdxs,
		EnumInfos:         file_sweep_v1_sweep_proto_enumTypes,
		MessageInfos:      file_sweep_v1_sweep_proto_msgTypes,
	}.Build()
	File_sweep_v1_sweep_proto = out.File
	file_sweep_v1_sweep_proto_goTypes = nil
	file_sweep_v1_sweep_proto_depIdxs = nil
}
