// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: sweep/v1/sweep.proto

package sweepv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IndexState int32

const (
	IndexState_INDEX_STATE_UNKNOWN     IndexState = 0
	IndexState_INDEX_STATE_NOT_INDEXED IndexState = 1
	IndexState_INDEX_STATE_INDEXING    IndexState = 2
	IndexState_INDEX_STATE_READY       IndexState = 3
	IndexState_INDEX_STATE_STALE       IndexState = 4
)

// Enum value maps for IndexState.
var (
	IndexState_name = map[int32]string{
		0: "INDEX_STATE_UNKNOWN",
		1: "INDEX_STATE_NOT_INDEXED",
		2: "INDEX_STATE_INDEXING",
		3: "INDEX_STATE_READY",
		4: "INDEX_STATE_STALE",
	}
	IndexState_value = map[string]int32{
		"INDEX_STATE_UNKNOWN":     0,
		"INDEX_STATE_NOT_INDEXED": 1,
		"INDEX_STATE_INDEXING":    2,
		"INDEX_STATE_READY":       3,
		"INDEX_STATE_STALE":       4,
	}
)

func (x IndexState) Enum() *IndexState {
	p := new(IndexState)
	*p = x
	return p
}

func (x IndexState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndexState) Descriptor() protoreflect.EnumDescriptor {
	return file_sweep_v1_sweep_proto_enumTypes[0].Descriptor()
}

func (IndexState) Type() protoreflect.EnumType {
	return &file_sweep_v1_sweep_proto_enumTypes[0]
}

func (x IndexState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IndexState.Descriptor instead.
func (IndexState) EnumDescriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{0}
}

// SortField specifies the field to sort files by.
type SortField int32

const (
	// Sort by file size in bytes.
	SortField_SORT_SIZE SortField = 0
	// Sort by modification time (age).
	SortField_SORT_MOD_TIME SortField = 1
	// Sort by file path alphabetically.
	SortField_SORT_PATH SortField = 2
)

// Enum value maps for SortField.
var (
	SortField_name = map[int32]string{
		0: "SORT_SIZE",
		1: "SORT_MOD_TIME",
		2: "SORT_PATH",
	}
	SortField_value = map[string]int32{
		"SORT_SIZE":     0,
		"SORT_MOD_TIME": 1,
		"SORT_PATH":     2,
	}
)

func (x SortField) Enum() *SortField {
	p := new(SortField)
	*p = x
	return p
}

func (x SortField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SortField) Descriptor() protoreflect.EnumDescriptor {
	return file_sweep_v1_sweep_proto_enumTypes[1].Descriptor()
}

func (SortField) Type() protoreflect.EnumType {
	return &file_sweep_v1_sweep_proto_enumTypes[1]
}

func (x SortField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SortField.Descriptor instead.
func (SortField) EnumDescriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{1}
}

type FileEvent_EventType int32

const (
	FileEvent_CREATED  FileEvent_EventType = 0
	FileEvent_MODIFIED FileEvent_EventType = 1
	FileEvent_DELETED  FileEvent_EventType = 2
	FileEvent_RENAMED  FileEvent_EventType = 3
)

// Enum value maps for FileEvent_EventType.
var (
	FileEvent_EventType_name = map[int32]string{
		0: "CREATED",
		1: "MODIFIED",
		2: "DELETED",
		3: "RENAMED",
	}
	FileEvent_EventType_value = map[string]int32{
		"CREATED":  0,
		"MODIFIED": 1,
		"DELETED":  2,
		"RENAMED":  3,
	}
)

func (x FileEvent_EventType) Enum() *FileEvent_EventType {
	p := new(FileEvent_EventType)
	*p = x
	return p
}

func (x FileEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_sweep_v1_sweep_proto_enumTypes[2].Descriptor()
}

func (FileEvent_EventType) Type() protoreflect.EnumType {
	return &file_sweep_v1_sweep_proto_enumTypes[2]
}

func (x FileEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileEvent_EventType.Descriptor instead.
func (FileEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{15, 0}
}

type TreeEvent_Type int32

const (
	TreeEvent_CREATED  TreeEvent_Type = 0
	TreeEvent_MODIFIED TreeEvent_Type = 1
	TreeEvent_DELETED  TreeEvent_Type = 2
)

// Enum value maps for TreeEvent_Type.
var (
	TreeEvent_Type_name = map[int32]string{
		0: "CREATED",
		1: "MODIFIED",
		2: "DELETED",
	}
	TreeEvent_Type_value = map[string]int32{
		"CREATED":  0,
		"MODIFIED": 1,
		"DELETED":  2,
	}
)

func (x TreeEvent_Type) Enum() *TreeEvent_Type {
	p := new(TreeEvent_Type)
	*p = x
	return p
}

func (x TreeEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TreeEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_sweep_v1_sweep_proto_enumTypes[3].Descriptor()
}

func (TreeEvent_Type) Type() protoreflect.EnumType {
	return &file_sweep_v1_sweep_proto_enumTypes[3]
}

func (x TreeEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TreeEvent_Type.Descriptor instead.
func (TreeEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{20, 0}
}

type GetLargeFilesRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Path    string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	MinSize int64                  `protobuf:"varint,2,opt,name=min_size,json=minSize,proto3" json:"min_size,omitempty"`
	Exclude []string               `protobuf:"bytes,3,rep,name=exclude,proto3" json:"exclude,omitempty"`
	Limit   int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	// Pattern matching (include patterns - files must match at least one if specified)
	Include []string `protobuf:"bytes,5,rep,name=include,proto3" json:"include,omitempty"`
	// File extensions to include (e.g., ".mp4", ".mkv")
	Extensions []string `protobuf:"bytes,6,rep,name=extensions,proto3" json:"extensions,omitempty"`
	// Type groups to include (e.g., "video", "audio", "archive")
	TypeGroups []string `protobuf:"bytes,7,rep,name=type_groups,json=typeGroups,proto3" json:"type_groups,omitempty"`
	// Age filtering
	// Only include files older than this many seconds
	OlderThanSeconds int64 `protobuf:"varint,8,opt,name=older_than_seconds,json=olderThanSeconds,proto3" json:"older_than_seconds,omitempty"`
	// Only include files newer than this many seconds
	NewerThanSeconds int64 `protobuf:"varint,9,opt,name=newer_than_seconds,json=newerThanSeconds,proto3" json:"newer_than_seconds,omitempty"`
	// Depth control (0 means unlimited)
	MaxDepth int32 `protobuf:"varint,10,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	// Sorting
	SortBy         SortField `protobuf:"varint,11,opt,name=sort_by,json=sortBy,proto3,enum=sweep.v1.SortField" json:"sort_by,omitempty"`
	SortDescending bool      `protobuf:"varint,12,opt,name=sort_descending,json=sortDescending,proto3" json:"sort_descending,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetLargeFilesRequest) Reset() {
	*x = GetLargeFilesRequest{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLargeFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLargeFilesRequest) ProtoMessage() {}

func (x *GetLargeFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLargeFilesRequest.ProtoReflect.Descriptor instead.
func (*GetLargeFilesRequest) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{0}
}

func (x *GetLargeFilesRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetLargeFilesRequest) GetMinSize() int64 {
	if x != nil {
		return x.MinSize
	}
	return 0
}

func (x *GetLargeFilesRequest) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *GetLargeFilesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetLargeFilesRequest) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *GetLargeFilesRequest) GetExtensions() []string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

func (x *GetLargeFilesRequest) GetTypeGroups() []string {
	if x != nil {
		return x.TypeGroups
	}
	return nil
}

func (x *GetLargeFilesRequest) GetOlderThanSeconds() int64 {
	if x != nil {
		return x.OlderThanSeconds
	}
	return 0
}

func (x *GetLargeFilesRequest) GetNewerThanSeconds() int64 {
	if x != nil {
		return x.NewerThanSeconds
	}
	return 0
}

func (x *GetLargeFilesRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *GetLargeFilesRequest) GetSortBy() SortField {
	if x != nil {
		return x.SortBy
	}
	return SortField_SORT_SIZE
}

func (x *GetLargeFilesRequest) GetSortDescending() bool {
	if x != nil {
		return x.SortDescending
	}
	return false
}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       int64                  `protobuf:"varint,3,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	CreateTime    int64                  `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Owner         string                 `protobuf:"bytes,5,opt,name=owner,proto3" json:"owner,omitempty"`
	Group         string                 `protobuf:"bytes,6,opt,name=group,proto3" json:"group,omitempty"`
	Mode          uint32                 `protobuf:"varint,7,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{1}
}

func (x *FileInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileInfo) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileInfo) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *FileInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *FileInfo) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *FileInfo) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *FileInfo) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type GetIndexStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIndexStatusRequest) Reset() {
	*x = GetIndexStatusRequest{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIndexStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIndexStatusRequest) ProtoMessage() {}

func (x *GetIndexStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIndexStatusRequest.ProtoReflect.Descriptor instead.
func (*GetIndexStatusRequest) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{2}
}

func (x *GetIndexStatusRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type IndexStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	State         IndexState             `protobuf:"varint,2,opt,name=state,proto3,enum=sweep.v1.IndexState" json:"state,omitempty"`
	FilesIndexed  int64                  `protobuf:"varint,3,opt,name=files_indexed,json=filesIndexed,proto3" json:"files_indexed,omitempty"`
	DirsIndexed   int64                  `protobuf:"varint,4,opt,name=dirs_indexed,json=dirsIndexed,proto3" json:"dirs_indexed,omitempty"`
	TotalSize     int64                  `protobuf:"varint,5,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	LastUpdated   int64                  `protobuf:"varint,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	Progress      float32                `protobuf:"fixed32,7,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexStatus) Reset() {
	*x = IndexStatus{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexStatus) ProtoMessage() {}

func (x *IndexStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexStatus.ProtoReflect.Descriptor instead.
func (*IndexStatus) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{3}
}

func (x *IndexStatus) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *IndexStatus) GetState() IndexState {
	if x != nil {
		return x.State
	}
	return IndexState_INDEX_STATE_UNKNOWN
}

func (x *IndexStatus) GetFilesIndexed() int64 {
	if x != nil {
		return x.FilesIndexed
	}
	return 0
}

func (x *IndexStatus) GetDirsIndexed() int64 {
	if x != nil {
		return x.DirsIndexed
	}
	return 0
}

func (x *IndexStatus) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *IndexStatus) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

func (x *IndexStatus) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type TriggerIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Force         bool                   `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerIndexRequest) Reset() {
	*x = TriggerIndexRequest{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerIndexRequest) ProtoMessage() {}

func (x *TriggerIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerIndexRequest.ProtoReflect.Descriptor instead.
func (*TriggerIndexRequest) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerIndexRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TriggerIndexRequest) GetForce() bool {
	if x != nil {
		return x.Force
	}
	return false
}

type TriggerIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Started       bool                   `protobuf:"varint,1,opt,name=started,proto3" json:"started,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerIndexResponse) Reset() {
	*x = TriggerIndexResponse{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerIndexResponse) ProtoMessage() {}

func (x *TriggerIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerIndexResponse.ProtoReflect.Descriptor instead.
func (*TriggerIndexResponse) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{5}
}

func (x *TriggerIndexResponse) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *TriggerIndexResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WatchIndexProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchIndexProgressRequest) Reset() {
	*x = WatchIndexProgressRequest{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchIndexProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchIndexProgressRequest) ProtoMessage() {}

func (x *WatchIndexProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchIndexProgressRequest.ProtoReflect.Descriptor instead.
func (*WatchIndexProgressRequest) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{6}
}

func (x *WatchIndexProgressRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type IndexProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	State         IndexState             `protobuf:"varint,2,opt,name=state,proto3,enum=sweep.v1.IndexState" json:"state,omitempty"`
	DirsScanned   int64                  `protobuf:"varint,3,opt,name=dirs_scanned,json=dirsScanned,proto3" json:"dirs_scanned,omitempty"`
	FilesScanned  int64                  `protobuf:"varint,4,opt,name=files_scanned,json=filesScanned,proto3" json:"files_scanned,omitempty"`
	CurrentPath   string                 `protobuf:"bytes,5,opt,name=current_path,json=currentPath,proto3" json:"current_path,omitempty"`
	Progress      float32                `protobuf:"fixed32,6,opt,name=progress,proto3" json:"progress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexProgress) Reset() {
	*x = IndexProgress{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexProgress) ProtoMessage() {}

func (x *IndexProgress) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexProgress.ProtoReflect.Descriptor instead.
func (*IndexProgress) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{7}
}

func (x *IndexProgress) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *IndexProgress) GetState() IndexState {
	if x != nil {
		return x.State
	}
	return IndexState_INDEX_STATE_UNKNOWN
}

func (x *IndexProgress) GetDirsScanned() int64 {
	if x != nil {
		return x.DirsScanned
	}
	return 0
}

func (x *IndexProgress) GetFilesScanned() int64 {
	if x != nil {
		return x.FilesScanned
	}
	return 0
}

func (x *IndexProgress) GetCurrentPath() string {
	if x != nil {
		return x.CurrentPath
	}
	return ""
}

func (x *IndexProgress) GetProgress() float32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

type GetDaemonStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDaemonStatusRequest) Reset() {
	*x = GetDaemonStatusRequest{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDaemonStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDaemonStatusRequest) ProtoMessage() {}

func (x *GetDaemonStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDaemonStatusRequest.ProtoReflect.Descriptor instead.
func (*GetDaemonStatusRequest) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{8}
}

type DaemonStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Running           bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	UptimeSeconds     int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	MemoryBytes       int64                  `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	WatchedPaths      []string               `protobuf:"bytes,4,rep,name=watched_paths,json=watchedPaths,proto3" json:"watched_paths,omitempty"`
	CacheSizeBytes    int64                  `protobuf:"varint,5,opt,name=cache_size_bytes,json=cacheSizeBytes,proto3" json:"cache_size_bytes,omitempty"`
	TotalFilesIndexed int64                  `protobuf:"varint,6,opt,name=total_files_indexed,json=totalFilesIndexed,proto3" json:"total_files_indexed,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DaemonStatus) Reset() {
	*x = DaemonStatus{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonStatus) ProtoMessage() {}

func (x *DaemonStatus) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonStatus.ProtoReflect.Descriptor instead.
func (*DaemonStatus) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{9}
}

func (x *DaemonStatus) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *DaemonStatus) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *DaemonStatus) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *DaemonStatus) GetWatchedPaths() []string {
	if x != nil {
		return x.WatchedPaths
	}
	return nil
}

func (x *DaemonStatus) GetCacheSizeBytes() int64 {
	if x != nil {
		return x.CacheSizeBytes
	}
	return 0
}

func (x *DaemonStatus) GetTotalFilesIndexed() int64 {
	if x != nil {
		return x.TotalFilesIndexed
	}
	return 0
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{10}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{11}
}

func (x *ShutdownResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ClearCacheRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCacheRequest) Reset() {
	*x = ClearCacheRequest{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCacheRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCacheRequest) ProtoMessage() {}

func (x *ClearCacheRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCacheRequest.ProtoReflect.Descriptor instead.
func (*ClearCacheRequest) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{12}
}

func (x *ClearCacheRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ClearCacheResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EntriesCleared int64                  `protobuf:"varint,2,opt,name=entries_cleared,json=entriesCleared,proto3" json:"entries_cleared,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClearCacheResponse) Reset() {
	*x = ClearCacheResponse{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCacheResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCacheResponse) ProtoMessage() {}

func (x *ClearCacheResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCacheResponse.ProtoReflect.Descriptor instead.
func (*ClearCacheResponse) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{13}
}

func (x *ClearCacheResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClearCacheResponse) GetEntriesCleared() int64 {
	if x != nil {
		return x.EntriesCleared
	}
	return 0
}

// Request to watch for file system changes
type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          string                 `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	MinSize       int64                  `protobuf:"varint,2,opt,name=min_size,json=minSize,proto3" json:"min_size,omitempty"`
	Exclude       []string               `protobuf:"bytes,3,rep,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{14}
}

func (x *WatchRequest) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *WatchRequest) GetMinSize() int64 {
	if x != nil {
		return x.MinSize
	}
	return 0
}

func (x *WatchRequest) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

// Event emitted when a file changes
type FileEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          FileEvent_EventType    `protobuf:"varint,1,opt,name=type,proto3,enum=sweep.v1.FileEvent_EventType" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       int64                  `protobuf:"varint,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEvent) Reset() {
	*x = FileEvent{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEvent) ProtoMessage() {}

func (x *FileEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEvent.ProtoReflect.Descriptor instead.
func (*FileEvent) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{15}
}

func (x *FileEvent) GetType() FileEvent_EventType {
	if x != nil {
		return x.Type
	}
	return FileEvent_CREATED
}

func (x *FileEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileEvent) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEvent) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

// Tree node for hierarchical display
type TreeNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsDir bool                   `protobuf:"varint,3,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	// For files
	Size     int64  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ModTime  int64  `protobuf:"varint,5,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	FileType string `protobuf:"bytes,6,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	// For directories
	LargeFileSize  int64 `protobuf:"varint,7,opt,name=large_file_size,json=largeFileSize,proto3" json:"large_file_size,omitempty"`
	LargeFileCount int32 `protobuf:"varint,8,opt,name=large_file_count,json=largeFileCount,proto3" json:"large_file_count,omitempty"`
	// Children (only populated if expanded)
	Children      []*TreeNode `protobuf:"bytes,9,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeNode) Reset() {
	*x = TreeNode{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeNode) ProtoMessage() {}

func (x *TreeNode) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeNode.ProtoReflect.Descriptor instead.
func (*TreeNode) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{16}
}

func (x *TreeNode) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TreeNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TreeNode) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *TreeNode) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TreeNode) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *TreeNode) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *TreeNode) GetLargeFileSize() int64 {
	if x != nil {
		return x.LargeFileSize
	}
	return 0
}

func (x *TreeNode) GetLargeFileCount() int32 {
	if x != nil {
		return x.LargeFileCount
	}
	return 0
}

func (x *TreeNode) GetChildren() []*TreeNode {
	if x != nil {
		return x.Children
	}
	return nil
}

type GetTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          string                 `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	MinSize       int64                  `protobuf:"varint,2,opt,name=min_size,json=minSize,proto3" json:"min_size,omitempty"`
	Exclude       []string               `protobuf:"bytes,3,rep,name=exclude,proto3" json:"exclude,omitempty"`
	MaxDepth      int32                  `protobuf:"varint,4,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"` // 0 = unlimited
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTreeRequest) Reset() {
	*x = GetTreeRequest{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeRequest) ProtoMessage() {}

func (x *GetTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeRequest.ProtoReflect.Descriptor instead.
func (*GetTreeRequest) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{17}
}

func (x *GetTreeRequest) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *GetTreeRequest) GetMinSize() int64 {
	if x != nil {
		return x.MinSize
	}
	return 0
}

func (x *GetTreeRequest) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

func (x *GetTreeRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

type GetTreeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          *TreeNode              `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	TotalIndexed  int64                  `protobuf:"varint,2,opt,name=total_indexed,json=totalIndexed,proto3" json:"total_indexed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTreeResponse) Reset() {
	*x = GetTreeResponse{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTreeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTreeResponse) ProtoMessage() {}

func (x *GetTreeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTreeResponse.ProtoReflect.Descriptor instead.
func (*GetTreeResponse) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{18}
}

func (x *GetTreeResponse) GetRoot() *TreeNode {
	if x != nil {
		return x.Root
	}
	return nil
}

func (x *GetTreeResponse) GetTotalIndexed() int64 {
	if x != nil {
		return x.TotalIndexed
	}
	return 0
}

// Request to watch for tree changes
type WatchTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Root          string                 `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	MinSize       int64                  `protobuf:"varint,2,opt,name=min_size,json=minSize,proto3" json:"min_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchTreeRequest) Reset() {
	*x = WatchTreeRequest{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchTreeRequest) ProtoMessage() {}

func (x *WatchTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchTreeRequest.ProtoReflect.Descriptor instead.
func (*WatchTreeRequest) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{19}
}

func (x *WatchTreeRequest) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *WatchTreeRequest) GetMinSize() int64 {
	if x != nil {
		return x.MinSize
	}
	return 0
}

// Event emitted when a tree node changes
type TreeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          TreeEvent_Type         `protobuf:"varint,1,opt,name=type,proto3,enum=sweep.v1.TreeEvent_Type" json:"type,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ModTime       int64                  `protobuf:"varint,4,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	ParentPath    string                 `protobuf:"bytes,5,opt,name=parent_path,json=parentPath,proto3" json:"parent_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TreeEvent) Reset() {
	*x = TreeEvent{}
	mi := &file_sweep_v1_sweep_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TreeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TreeEvent) ProtoMessage() {}

func (x *TreeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sweep_v1_sweep_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TreeEvent.ProtoReflect.Descriptor instead.
func (*TreeEvent) Descriptor() ([]byte, []int) {
	return file_sweep_v1_sweep_proto_rawDescGZIP(), []int{20}
}

func (x *TreeEvent) GetType() TreeEvent_Type {
	if x != nil {
		return x.Type
	}
	return TreeEvent_CREATED
}

func (x *TreeEvent) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TreeEvent) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TreeEvent) GetModTime() int64 {
	if x != nil {
		return x.ModTime
	}
	return 0
}

func (x *TreeEvent) GetParentPath() string {
	if x != nil {
		return x.ParentPath
	}
	return ""
}

var File_sweep_v1_sweep_proto protoreflect.FileDescriptor

const file_sweep_v1_sweep_proto_rawDesc = "" +
	"\n" +
	"\x14sweep/v1/sweep.proto\x12\bsweep.v1\"\xa0\x03\n" +
	"\x14GetLargeFilesRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\bmin_size\x18\x02 \x01(\x03R\aminSize\x12\x18\n" +
	"\aexclude\x18\x03 \x03(\tR\aexclude\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x18\n" +
	"\ainclude\x18\x05 \x03(\tR\ainclude\x12\x1e\n" +
	"\n" +
	"extensions\x18\x06 \x03(\tR\n" +
	"extensions\x12\x1f\n" +
	"\vtype_groups\x18\a \x03(\tR\n" +
	"typeGroups\x12,\n" +
	"\x12older_than_seconds\x18\b \x01(\x03R\x10olderThanSeconds\x12,\n" +
	"\x12newer_than_seconds\x18\t \x01(\x03R\x10newerThanSeconds\x12\x1b\n" +
	"\tmax_depth\x18\n" +
	" \x01(\x05R\bmaxDepth\x12,\n" +
	"\asort_by\x18\v \x01(\x0e2\x13.sweep.v1.SortFieldR\x06sortBy\x12'\n" +
	"\x0fsort_descending\x18\f \x01(\bR\x0esortDescending\"\xae\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x19\n" +
	"\bmod_time\x18\x03 \x01(\x03R\amodTime\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\x03R\n" +
	"createTime\x12\x14\n" +
	"\x05owner\x18\x05 \x01(\tR\x05owner\x12\x14\n" +
	"\x05group\x18\x06 \x01(\tR\x05group\x12\x12\n" +
	"\x04mode\x18\a \x01(\rR\x04mode\"+\n" +
	"\x15GetIndexStatusRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xf3\x01\n" +
	"\vIndexStatus\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12*\n" +
	"\x05state\x18\x02 \x01(\x0e2\x14.sweep.v1.IndexStateR\x05state\x12#\n" +
	"\rfiles_indexed\x18\x03 \x01(\x03R\ffilesIndexed\x12!\n" +
	"\fdirs_indexed\x18\x04 \x01(\x03R\vdirsIndexed\x12\x1d\n" +
	"\n" +
	"total_size\x18\x05 \x01(\x03R\ttotalSize\x12!\n" +
	"\flast_updated\x18\x06 \x01(\x03R\vlastUpdated\x12\x1a\n" +
	"\bprogress\x18\a \x01(\x02R\bprogress\"?\n" +
	"\x13TriggerIndexRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05force\x18\x02 \x01(\bR\x05force\"J\n" +
	"\x14TriggerIndexResponse\x12\x18\n" +
	"\astarted\x18\x01 \x01(\bR\astarted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x19WatchIndexProgressRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xd6\x01\n" +
	"\rIndexProgress\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12*\n" +
	"\x05state\x18\x02 \x01(\x0e2\x14.sweep.v1.IndexStateR\x05state\x12!\n" +
	"\fdirs_scanned\x18\x03 \x01(\x03R\vdirsScanned\x12#\n" +
	"\rfiles_scanned\x18\x04 \x01(\x03R\ffilesScanned\x12!\n" +
	"\fcurrent_path\x18\x05 \x01(\tR\vcurrentPath\x12\x1a\n" +
	"\bprogress\x18\x06 \x01(\x02R\bprogress\"\x18\n" +
	"\x16GetDaemonStatusRequest\"\xf1\x01\n" +
	"\fDaemonStatus\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x03R\vmemoryBytes\x12#\n" +
	"\rwatched_paths\x18\x04 \x03(\tR\fwatchedPaths\x12(\n" +
	"\x10cache_size_bytes\x18\x05 \x01(\x03R\x0ecacheSizeBytes\x12.\n" +
	"\x13total_files_indexed\x18\x06 \x01(\x03R\x11totalFilesIndexed\"\x11\n" +
	"\x0fShutdownRequest\",\n" +
	"\x10ShutdownResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"'\n" +
	"\x11ClearCacheRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"W\n" +
	"\x12ClearCacheResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fentries_cleared\x18\x02 \x01(\x03R\x0eentriesCleared\"W\n" +
	"\fWatchRequest\x12\x12\n" +
	"\x04root\x18\x01 \x01(\tR\x04root\x12\x19\n" +
	"\bmin_size\x18\x02 \x01(\x03R\aminSize\x12\x18\n" +
	"\aexclude\x18\x03 \x03(\tR\aexclude\"\xc3\x01\n" +
	"\tFileEvent\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.sweep.v1.FileEvent.EventTypeR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x19\n" +
	"\bmod_time\x18\x04 \x01(\x03R\amodTime\"@\n" +
	"\tEventType\x12\v\n" +
	"\aCREATED\x10\x00\x12\f\n" +
	"\bMODIFIED\x10\x01\x12\v\n" +
	"\aDELETED\x10\x02\x12\v\n" +
	"\aRENAMED\x10\x03\"\x97\x02\n" +
	"\bTreeNode\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x03 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x19\n" +
	"\bmod_time\x18\x05 \x01(\x03R\amodTime\x12\x1b\n" +
	"\tfile_type\x18\x06 \x01(\tR\bfileType\x12&\n" +
	"\x0flarge_file_size\x18\a \x01(\x03R\rlargeFileSize\x12(\n" +
	"\x10large_file_count\x18\b \x01(\x05R\x0elargeFileCount\x12.\n" +
	"\bchildren\x18\t \x03(\v2\x12.sweep.v1.TreeNodeR\bchildren\"v\n" +
	"\x0eGetTreeRequest\x12\x12\n" +
	"\x04root\x18\x01 \x01(\tR\x04root\x12\x19\n" +
	"\bmin_size\x18\x02 \x01(\x03R\aminSize\x12\x18\n" +
	"\aexclude\x18\x03 \x03(\tR\aexclude\x12\x1b\n" +
	"\tmax_depth\x18\x04 \x01(\x05R\bmaxDepth\"^\n" +
	"\x0fGetTreeResponse\x12&\n" +
	"\x04root\x18\x01 \x01(\v2\x12.sweep.v1.TreeNodeR\x04root\x12#\n" +
	"\rtotal_indexed\x18\x02 \x01(\x03R\ftotalIndexed\"A\n" +
	"\x10WatchTreeRequest\x12\x12\n" +
	"\x04root\x18\x01 \x01(\tR\x04root\x12\x19\n" +
	"\bmin_size\x18\x02 \x01(\x03R\aminSize\"\xcd\x01\n" +
	"\tTreeEvent\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.sweep.v1.TreeEvent.TypeR\x04type\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x19\n" +
	"\bmod_time\x18\x04 \x01(\x03R\amodTime\x12\x1f\n" +
	"\vparent_path\x18\x05 \x01(\tR\n" +
	"parentPath\".\n" +
	"\x04Type\x12\v\n" +
	"\aCREATED\x10\x00\x12\f\n" +
	"\bMODIFIED\x10\x01\x12\v\n" +
	"\aDELETED\x10\x02*\x8a\x01\n" +
	"\n" +
	"IndexState\x12\x17\n" +
	"\x13INDEX_STATE_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x17INDEX_STATE_NOT_INDEXED\x10\x01\x12\x18\n" +
	"\x14INDEX_STATE_INDEXING\x10\x02\x12\x15\n" +
	"\x11INDEX_STATE_READY\x10\x03\x12\x15\n" +
	"\x11INDEX_STATE_STALE\x10\x04*<\n" +
	"\tSortField\x12\r\n" +
	"\tSORT_SIZE\x10\x00\x12\x11\n" +
	"\rSORT_MOD_TIME\x10\x01\x12\r\n" +
	"\tSORT_PATH\x10\x022\xde\x05\n" +
	"\vSweepDaemon\x12E\n" +
	"\rGetLargeFiles\x12\x1e.sweep.v1.GetLargeFilesRequest\x1a\x12.sweep.v1.FileInfo0\x01\x12H\n" +
	"\x0eGetIndexStatus\x12\x1f.sweep.v1.GetIndexStatusRequest\x1a\x15.sweep.v1.IndexStatus\x12M\n" +
	"\fTriggerIndex\x12\x1d.sweep.v1.TriggerIndexRequest\x1a\x1e.sweep.v1.TriggerIndexResponse\x12T\n" +
	"\x12WatchIndexProgress\x12#.sweep.v1.WatchIndexProgressRequest\x1a\x17.sweep.v1.IndexProgress0\x01\x12K\n" +
	"\x0fGetDaemonStatus\x12 .sweep.v1.GetDaemonStatusRequest\x1a\x16.sweep.v1.DaemonStatus\x12A\n" +
	"\bShutdown\x12\x19.sweep.v1.ShutdownRequest\x1a\x1a.sweep.v1.ShutdownResponse\x12G\n" +
	"\n" +
	"ClearCache\x12\x1b.sweep.v1.ClearCacheRequest\x1a\x1c.sweep.v1.ClearCacheResponse\x12@\n" +
	"\x0fWatchLargeFiles\x12\x16.sweep.v1.WatchRequest\x1a\x13.sweep.v1.FileEvent0\x01\x12>\n" +
	"\aGetTree\x12\x18.sweep.v1.GetTreeRequest\x1a\x19.sweep.v1.GetTreeResponse\x12>\n" +
	"\tWatchTree\x12\x1a.sweep.v1.WatchTreeRequest\x1a\x13.sweep.v1.TreeEvent0\x01B8Z6github.com/jamesainslie/sweep/pkg/api/sweep/v1;sweepv1b\x06proto3"

var (
	file_sweep_v1_sweep_proto_rawDescOnce sync.Once
	file_sweep_v1_sweep_proto_rawDescData []byte
)

func file_sweep_v1_sweep_proto_rawDescGZIP() []byte {
	file_sweep_v1_sweep_proto_rawDescOnce.Do(func() {
		file_sweep_v1_sweep_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sweep_v1_sweep_proto_rawDesc), len(file_sweep_v1_sweep_proto_rawDesc)))
	})
	return file_sweep_v1_sweep_proto_rawDescData
}

var file_sweep_v1_sweep_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_sweep_v1_sweep_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_sweep_v1_sweep_proto_goTypes = []any{
	(IndexState)(0),                   // 0: sweep.v1.IndexState
	(SortField)(0),                    // 1: sweep.v1.SortField
	(FileEvent_EventType)(0),          // 2: sweep.v1.FileEvent.EventType
	(TreeEvent_Type)(0),               // 3: sweep.v1.TreeEvent.Type
	(*GetLargeFilesRequest)(nil),      // 4: sweep.v1.GetLargeFilesRequest
	(*FileInfo)(nil),                  // 5: sweep.v1.FileInfo
	(*GetIndexStatusRequest)(nil),     // 6: sweep.v1.GetIndexStatusRequest
	(*IndexStatus)(nil),               // 7: sweep.v1.IndexStatus
	(*TriggerIndexRequest)(nil),       // 8: sweep.v1.TriggerIndexRequest
	(*TriggerIndexResponse)(nil),      // 9: sweep.v1.TriggerIndexResponse
	(*WatchIndexProgressRequest)(nil), // 10: sweep.v1.WatchIndexProgressRequest
	(*IndexProgress)(nil),             // 11: sweep.v1.IndexProgress
	(*GetDaemonStatusRequest)(nil),    // 12: sweep.v1.GetDaemonStatusRequest
	(*DaemonStatus)(nil),              // 13: sweep.v1.DaemonStatus
	(*ShutdownRequest)(nil),           // 14: sweep.v1.ShutdownRequest
	(*ShutdownResponse)(nil),          // 15: sweep.v1.ShutdownResponse
	(*ClearCacheRequest)(nil),         // 16: sweep.v1.ClearCacheRequest
	(*ClearCacheResponse)(nil),        // 17: sweep.v1.ClearCacheResponse
	(*WatchRequest)(nil),              // 18: sweep.v1.WatchRequest
	(*FileEvent)(nil),                 // 19: sweep.v1.FileEvent
	(*TreeNode)(nil),                  // 20: sweep.v1.TreeNode
	(*GetTreeRequest)(nil),            // 21: sweep.v1.GetTreeRequest
	(*GetTreeResponse)(nil),           // 22: sweep.v1.GetTreeResponse
	(*WatchTreeRequest)(nil),          // 23: sweep.v1.WatchTreeRequest
	(*TreeEvent)(nil),                 // 24: sweep.v1.TreeEvent
}
var file_sweep_v1_sweep_proto_depIdxs = []int32{
	1,  // 0: sweep.v1.GetLargeFilesRequest.sort_by:type_name -> sweep.v1.SortField
	0,  // 1: sweep.v1.IndexStatus.state:type_name -> sweep.v1.IndexState
	0,  // 2: sweep.v1.IndexProgress.state:type_name -> sweep.v1.IndexState
	2,  // 3: sweep.v1.FileEvent.type:type_name -> sweep.v1.FileEvent.EventType
	20, // 4: sweep.v1.TreeNode.children:type_name -> sweep.v1.TreeNode
	20, // 5: sweep.v1.GetTreeResponse.root:type_name -> sweep.v1.TreeNode
	3,  // 6: sweep.v1.TreeEvent.type:type_name -> sweep.v1.TreeEvent.Type
	4,  // 7: sweep.v1.SweepDaemon.GetLargeFiles:input_type -> sweep.v1.GetLargeFilesRequest
	6,  // 8: sweep.v1.SweepDaemon.GetIndexStatus:input_type -> sweep.v1.GetIndexStatusRequest
	8,  // 9: sweep.v1.SweepDaemon.TriggerIndex:input_type -> sweep.v1.TriggerIndexRequest
	10, // 10: sweep.v1.SweepDaemon.WatchIndexProgress:input_type -> sweep.v1.WatchIndexProgressRequest
	12, // 11: sweep.v1.SweepDaemon.GetDaemonStatus:input_type -> sweep.v1.GetDaemonStatusRequest
	14, // 12: sweep.v1.SweepDaemon.Shutdown:input_type -> sweep.v1.ShutdownRequest
	16, // 13: sweep.v1.SweepDaemon.ClearCache:input_type -> sweep.v1.ClearCacheRequest
	18, // 14: sweep.v1.SweepDaemon.WatchLargeFiles:input_type -> sweep.v1.WatchRequest
	21, // 15: sweep.v1.SweepDaemon.GetTree:input_type -> sweep.v1.GetTreeRequest
	23, // 16: sweep.v1.SweepDaemon.WatchTree:input_type -> sweep.v1.WatchTreeRequest
	5,  // 17: sweep.v1.SweepDaemon.GetLargeFiles:output_type -> sweep.v1.FileInfo
	7,  // 18: sweep.v1.SweepDaemon.GetIndexStatus:output_type -> sweep.v1.IndexStatus
	9,  // 19: sweep.v1.SweepDaemon.TriggerIndex:output_type -> sweep.v1.TriggerIndexResponse
	11, // 20: sweep.v1.SweepDaemon.WatchIndexProgress:output_type -> sweep.v1.IndexProgress
	13, // 21: sweep.v1.SweepDaemon.GetDaemonStatus:output_type -> sweep.v1.DaemonStatus
	15, // 22: sweep.v1.SweepDaemon.Shutdown:output_type -> sweep.v1.ShutdownResponse
	17, // 23: sweep.v1.SweepDaemon.ClearCache:output_type -> sweep.v1.ClearCacheResponse
	19, // 24: sweep.v1.SweepDaemon.WatchLargeFiles:output_type -> sweep.v1.FileEvent
	22, // 25: sweep.v1.SweepDaemon.GetTree:output_type -> sweep.v1.GetTreeResponse
	24, // 26: sweep.v1.SweepDaemon.WatchTree:output_type -> sweep.v1.TreeEvent
	17, // [17:27] is the sub-list for method output_type
	7,  // [7:17] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_sweep_v1_sweep_proto_init() }
func file_sweep_v1_sweep_proto_init() {
	if File_sweep_v1_sweep_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sweep_v1_sweep_proto_rawDesc), len(file_sweep_v1_sweep_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sweep_v1_sweep_proto_goTypes,
		DependencyIndexes: file_sweep_v1_sweep_proto_depIdxs,
		EnumInfos:         file_sweep_v1_sweep_proto_enumTypes,
		MessageInfos:      file_sweep_v1_sweep_proto_msgTypes,
	}.Build()
	File_sweep_v1_sweep_proto = out.File
	file_sweep_v1_sweep_proto_goTypes = nil
	file_sweep_v1_sweep_proto_depIdxs = nil
}
