// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: sweep/v1/sweep.proto

package sweepv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SweepDaemon_GetLargeFiles_FullMethodName      = "/sweep.v1.SweepDaemon/GetLargeFiles"
	SweepDaemon_GetIndexStatus_FullMethodName     = "/sweep.v1.SweepDaemon/GetIndexStatus"
	SweepDaemon_TriggerIndex_FullMethodName       = "/sweep.v1.SweepDaemon/TriggerIndex"
	SweepDaemon_WatchIndexProgress_FullMethodName = "/sweep.v1.SweepDaemon/WatchIndexProgress"
	SweepDaemon_GetDaemonStatus_FullMethodName    = "/sweep.v1.SweepDaemon/GetDaemonStatus"
	SweepDaemon_Shutdown_FullMethodName           = "/sweep.v1.SweepDaemon/Shutdown"
	SweepDaemon_ClearCache_FullMethodName         = "/sweep.v1.SweepDaemon/ClearCache"
)

// SweepDaemonClient is the client API for SweepDaemon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SweepDaemon provides disk analysis services
type SweepDaemonClient interface {
	// Stream large files matching criteria
	GetLargeFiles(ctx context.Context, in *GetLargeFilesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileInfo], error)
	// Get index status for a path
	GetIndexStatus(ctx context.Context, in *GetIndexStatusRequest, opts ...grpc.CallOption) (*IndexStatus, error)
	// Trigger indexing of a path
	TriggerIndex(ctx context.Context, in *TriggerIndexRequest, opts ...grpc.CallOption) (*TriggerIndexResponse, error)
	// Stream live indexing progress
	WatchIndexProgress(ctx context.Context, in *WatchIndexProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IndexProgress], error)
	// Get daemon health/status
	GetDaemonStatus(ctx context.Context, in *GetDaemonStatusRequest, opts ...grpc.CallOption) (*DaemonStatus, error)
	// Graceful shutdown
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
	// Clear cache for a path
	ClearCache(ctx context.Context, in *ClearCacheRequest, opts ...grpc.CallOption) (*ClearCacheResponse, error)
}

type sweepDaemonClient struct {
	cc grpc.ClientConnInterface
}

func NewSweepDaemonClient(cc grpc.ClientConnInterface) SweepDaemonClient {
	return &sweepDaemonClient{cc}
}

func (c *sweepDaemonClient) GetLargeFiles(ctx context.Context, in *GetLargeFilesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileInfo], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SweepDaemon_ServiceDesc.Streams[0], SweepDaemon_GetLargeFiles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetLargeFilesRequest, FileInfo]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SweepDaemon_GetLargeFilesClient = grpc.ServerStreamingClient[FileInfo]

func (c *sweepDaemonClient) GetIndexStatus(ctx context.Context, in *GetIndexStatusRequest, opts ...grpc.CallOption) (*IndexStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IndexStatus)
	err := c.cc.Invoke(ctx, SweepDaemon_GetIndexStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sweepDaemonClient) TriggerIndex(ctx context.Context, in *TriggerIndexRequest, opts ...grpc.CallOption) (*TriggerIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerIndexResponse)
	err := c.cc.Invoke(ctx, SweepDaemon_TriggerIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sweepDaemonClient) WatchIndexProgress(ctx context.Context, in *WatchIndexProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[IndexProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SweepDaemon_ServiceDesc.Streams[1], SweepDaemon_WatchIndexProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchIndexProgressRequest, IndexProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SweepDaemon_WatchIndexProgressClient = grpc.ServerStreamingClient[IndexProgress]

func (c *sweepDaemonClient) GetDaemonStatus(ctx context.Context, in *GetDaemonStatusRequest, opts ...grpc.CallOption) (*DaemonStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DaemonStatus)
	err := c.cc.Invoke(ctx, SweepDaemon_GetDaemonStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sweepDaemonClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, SweepDaemon_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sweepDaemonClient) ClearCache(ctx context.Context, in *ClearCacheRequest, opts ...grpc.CallOption) (*ClearCacheResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearCacheResponse)
	err := c.cc.Invoke(ctx, SweepDaemon_ClearCache_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SweepDaemonServer is the server API for SweepDaemon service.
// All implementations must embed UnimplementedSweepDaemonServer
// for forward compatibility.
//
// SweepDaemon provides disk analysis services
type SweepDaemonServer interface {
	// Stream large files matching criteria
	GetLargeFiles(*GetLargeFilesRequest, grpc.ServerStreamingServer[FileInfo]) error
	// Get index status for a path
	GetIndexStatus(context.Context, *GetIndexStatusRequest) (*IndexStatus, error)
	// Trigger indexing of a path
	TriggerIndex(context.Context, *TriggerIndexRequest) (*TriggerIndexResponse, error)
	// Stream live indexing progress
	WatchIndexProgress(*WatchIndexProgressRequest, grpc.ServerStreamingServer[IndexProgress]) error
	// Get daemon health/status
	GetDaemonStatus(context.Context, *GetDaemonStatusRequest) (*DaemonStatus, error)
	// Graceful shutdown
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	// Clear cache for a path
	ClearCache(context.Context, *ClearCacheRequest) (*ClearCacheResponse, error)
	mustEmbedUnimplementedSweepDaemonServer()
}

// UnimplementedSweepDaemonServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSweepDaemonServer struct{}

func (UnimplementedSweepDaemonServer) GetLargeFiles(*GetLargeFilesRequest, grpc.ServerStreamingServer[FileInfo]) error {
	return status.Error(codes.Unimplemented, "method GetLargeFiles not implemented")
}
func (UnimplementedSweepDaemonServer) GetIndexStatus(context.Context, *GetIndexStatusRequest) (*IndexStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIndexStatus not implemented")
}
func (UnimplementedSweepDaemonServer) TriggerIndex(context.Context, *TriggerIndexRequest) (*TriggerIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerIndex not implemented")
}
func (UnimplementedSweepDaemonServer) WatchIndexProgress(*WatchIndexProgressRequest, grpc.ServerStreamingServer[IndexProgress]) error {
	return status.Error(codes.Unimplemented, "method WatchIndexProgress not implemented")
}
func (UnimplementedSweepDaemonServer) GetDaemonStatus(context.Context, *GetDaemonStatusRequest) (*DaemonStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDaemonStatus not implemented")
}
func (UnimplementedSweepDaemonServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedSweepDaemonServer) ClearCache(context.Context, *ClearCacheRequest) (*ClearCacheResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearCache not implemented")
}
func (UnimplementedSweepDaemonServer) mustEmbedUnimplementedSweepDaemonServer() {}
func (UnimplementedSweepDaemonServer) testEmbeddedByValue()                     {}

// UnsafeSweepDaemonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SweepDaemonServer will
// result in compilation errors.
type UnsafeSweepDaemonServer interface {
	mustEmbedUnimplementedSweepDaemonServer()
}

func RegisterSweepDaemonServer(s grpc.ServiceRegistrar, srv SweepDaemonServer) {
	// If the following call panics, it indicates UnimplementedSweepDaemonServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SweepDaemon_ServiceDesc, srv)
}

func _SweepDaemon_GetLargeFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLargeFilesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SweepDaemonServer).GetLargeFiles(m, &grpc.GenericServerStream[GetLargeFilesRequest, FileInfo]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SweepDaemon_GetLargeFilesServer = grpc.ServerStreamingServer[FileInfo]

func _SweepDaemon_GetIndexStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIndexStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SweepDaemonServer).GetIndexStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SweepDaemon_GetIndexStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SweepDaemonServer).GetIndexStatus(ctx, req.(*GetIndexStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SweepDaemon_TriggerIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SweepDaemonServer).TriggerIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SweepDaemon_TriggerIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SweepDaemonServer).TriggerIndex(ctx, req.(*TriggerIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SweepDaemon_WatchIndexProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchIndexProgressRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SweepDaemonServer).WatchIndexProgress(m, &grpc.GenericServerStream[WatchIndexProgressRequest, IndexProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SweepDaemon_WatchIndexProgressServer = grpc.ServerStreamingServer[IndexProgress]

func _SweepDaemon_GetDaemonStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDaemonStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SweepDaemonServer).GetDaemonStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SweepDaemon_GetDaemonStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SweepDaemonServer).GetDaemonStatus(ctx, req.(*GetDaemonStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SweepDaemon_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SweepDaemonServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SweepDaemon_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SweepDaemonServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SweepDaemon_ClearCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearCacheRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SweepDaemonServer).ClearCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SweepDaemon_ClearCache_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SweepDaemonServer).ClearCache(ctx, req.(*ClearCacheRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SweepDaemon_ServiceDesc is the grpc.ServiceDesc for SweepDaemon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SweepDaemon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sweep.v1.SweepDaemon",
	HandlerType: (*SweepDaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetIndexStatus",
			Handler:    _SweepDaemon_GetIndexStatus_Handler,
		},
		{
			MethodName: "TriggerIndex",
			Handler:    _SweepDaemon_TriggerIndex_Handler,
		},
		{
			MethodName: "GetDaemonStatus",
			Handler:    _SweepDaemon_GetDaemonStatus_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _SweepDaemon_Shutdown_Handler,
		},
		{
			MethodName: "ClearCache",
			Handler:    _SweepDaemon_ClearCache_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetLargeFiles",
			Handler:       _SweepDaemon_GetLargeFiles_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchIndexProgress",
			Handler:       _SweepDaemon_WatchIndexProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sweep/v1/sweep.proto",
}
